In [51]:
%matplotlib inline

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np

df = pd.read_csv("./data/Diamonds/diamonds.csv.bz2")

df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [52]:
# Train/Test

# Split "zu Fuß"
print(len(df))

df_train = df.iloc[:40000]
df_test = df.iloc[40000:]

53940

In [53]:
from sklearn.linear_model import LinearRegression

x_train = df_train["carat"].to_numpy().reshape(-1, 1)
y_train = df_train["price"]

model = LinearRegression()
model.fit(x_train, y_train)

x_test = df_test["carat"].to_numpy().reshape(-1, 1)
y_test = df_test["price"]
print(model.score(x_test, y_test))  # R^2 Bestimmtheitsmaß ist nicht gut in diesem Fall
# Problem: Testdatensatz ist nicht gut aufgeteeilt, da der erste Teil der Daten kleinere Karatwerte hat als der zweite Teil.

-1.0517239092305526

In [54]:
df = df.sample(frac=1)  # Shuffle the DataFrame

df.head()

       carat        cut color clarity  depth  table  price     x     y     z
37807   0.35      Ideal     G      IF   62.0   54.0   1001  4.54  4.56  2.82
37364   0.40    Premium     D     VS2   62.4   59.0    982  4.70  4.72  2.94
27349   1.07  Very Good     D      IF   59.0   59.0  17909  6.63  6.72  3.94
36971   0.42      Ideal     G    VVS2   61.4   54.0    962  4.81  4.90  2.98
52159   0.70  Very Good     E     VS2   58.8   56.0   2473  5.79  5.84  3.42

In [55]:
df_train = df.iloc[:40000]
df_test = df.iloc[40000:]

X_train = df_train["carat"].to_numpy().reshape(-1, 1)
y_train = df_train["price"]

model = LinearRegression()
model.fit(X_train, y_train)

X_test = df_test["carat"].to_numpy().reshape(-1, 1)
y_test = df_test["price"]
print(model.score(X_test, y_test))

0.8498971204055736

In [56]:
# Daten aufteilen mit sklearn

from sklearn.model_selection import train_test_split

train, test = train_test_split([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], test_size=0.2)

print(train)
print(test)

[10, 4, 2, 5, 7, 1, 6, 8]
[9, 3]

In [57]:
train_test_split([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [101, 102, 103, 104, 105, 106, 107, 108, 109, 1010], test_size=0.2)

[[3, 8, 9, 2, 10, 5, 1, 7],
 [6, 4],
 [103, 108, 109, 102, 1010, 105, 101, 107],
 [106, 104]]

In [62]:

X = df[["carat", "x"]]
y = df["price"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)

print(model.score(X_test, y_test))  # R^2

0.8552091594125883